### ISSUE TITLE
项目编译时出错

### ISSUE THREAD

**Issue by QJvic** [HPSCIL/cuESTARFM#2]
项目平台设为x64，编译项目时出错。
错误列表如下：
Error	LNK2019	unresolved external symbol "void __cdecl Re_fusion2(class CuLayer *,struct PARAMETER *)" (?Re_fusion2@@YAXPEAVCuLayer@@PEAUPARAMETER@@@Z) referenced in function main	ff	C:\Users\joe\Downloads\Compressed\cuSTARFM-master\Windows\fusion.obj	1	

Error	LNK1120	1 unresolved externals	ff	C:\Users\joe\Downloads\Compressed\cuSTARFM-master\Windows\x64\Debug\ff.exe	1	

之前c++用得少，通过错误提示猜测为Re_fusion2函数只进行了定义而没有实现。
配置环境已经配置好了，也可能是我哪里还没有准备到位。请问能否帮我解决下这个问题。期盼您的回复。

**Comment by gisers** [comment]
这个程序需要安装cuda，Re_fusion2这个函数是在kernel.cu里面实现的，项目需要包含该文件，如果方便的话，你可以加我的QQ进行讨论，994684265

**Comment by gisers** [comment]
请问您的问题解决了吗，是环境没装好的原因吗

**Comment by QJvic** [comment]
不好意思，到现在才回复。解决了，是c++项目没配置好的原因，找了方法把cu文件配好了。感谢。

**Comment by wgj6112345** [comment]
大佬，我用你的测试数据可以在程序里面运行成功，但是自己的数据不知道为什么不行。我输进去的全是一幅影像，想着应该满足输入参数的要求，结果报错了。。。（ps. 我用的是250m的NDVI数据）
